### ISSUE TITLE
missing install targets for `scripts/`

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/robblog#9]
After this is fixed it should be re-released via http://strands-project.github.io/rosdistro/

**Comment by marc-hanheide** [comment]
Or is it not needed?

**Comment by marc-hanheide** [comment]
If it's not needed, then the release is done finally.

**Comment by hawesie** [comment]
Weird, I thought I'd done that, but clearly I made an error (the target is there, but it's not installing stuff). I'll fix now.
